# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          image: todo-app:prod
          imagePullPolicy: Never
          ports:
          - containerPort: 80
          env:
#          envFrom:
#          - secretRef:
#              name: app-secret4
          - name: DB_NAME  
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key: DB_NAME  
          - name: COLLECTION_NAME 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key: COLLECTION_NAME 
          - name: CLIENTID 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key: CLIENTID 
          - name: CLIENTSECRET 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key: CLIENTSECRET 
          - name: LOGGLY_TOKEN 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key: LOGGLY_TOKEN
          - name:  SECRET_KEY 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key:  SECRET_KEY       
          - name:  FLASK_APP 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key:  FLASK_APP
          - name:  FLASK_ENV 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key:  FLASK_ENV
          - name:  LOG_LEVEL
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key:  LOG_LEVEL
          - name:  LOGGLY_TOKEN 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key:  LOGGLY_TOKEN
          - name:  URL 
            valueFrom: 
              secretKeyRef: 
                name: app-secret4 
                key:  URL
