---
- name: myPlaybook todo app deploy
  hosts: servers
  remote_user: ec2-user
  vars_prompt:

    - name: TRELLO_KEY
      prompt: Enter TRELLO KEY
      private: no

    - name: TRELLO_TOKEN
      prompt: Enter TRELLO TOKEN
      private: yes

    - name: TRELLO_BOARD_ID
      prompt: Enter TRELLO BOARD ID
      private: no

  tasks:
    - name: install Git
      ansible.builtin.yum:
        name: git
        state: present
      become: yes

    - name: install python3
      ansible.builtin.yum:
        name: python3
        state: present
      become: yes

    - name: install poetry
      ansible.builtin.shell:
        cmd: curl -sSL https://install.python-poetry.org | python3 -
        creates: ~/.local/bin/poetry

    - name: Create folder
      ansible.builtin.file:
        path: /opt/todo_app
        state: directory
        owner: ec2-user
      become: yes

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/wishy78/DevOps-Course-Starter.git'
        dest: /opt/todo_app/
        version: Module3
      become: yes

    - name: install dependencies
      ansible.builtin.shell:
        cmd: /home/ec2-user/.local/bin/poetry install
      args:
        chdir: /opt/todo_app/
      become: yes

    - name: Template a file to /opt/todo_app/.env.j2
      ansible.builtin.template:
        src: .env.j2
        dest: /opt/todo_app/.env
        mode: u=rw,g=rw,o=rw
        owner: ec2-user
      become: yes

    - name: Copy service file
      ansible.builtin.copy:
        src: todoapp.service
        dest: /etc/systemd/system/todoapp.service
        mode: '0644'
      become: yes

    - name: Make sure a service todoapp is running
      ansible.builtin.systemd:
        state: started
        name: todoapp
      become: yes

