name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.lock'
      - '.github\**'
      - '.idea\**'     
      - '.pytest_cache\**'
      - '.venv\**'
      - '.vscode\**'

  pull_request:
    paths-ignore:
      - '**.md'
      - '.github\**'
      - '.idea\**'     
      - '.vscode\**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: BuildTestImage
      run: docker build --target test --tag todo-app:test .
    
    - name: BuildAndTestImage
      run: docker run --env-file .env.test todo-app:test tests

  Publish:
    #if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    if: ${{ github.ref == 'refs/heads/moudle8' && github.event_name == 'push' }}
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - name: publish to docker hub
      run: echo "Publishing!"

    - name: Build Image
      run: docker build --tag Moudle8 .

    - name: Change Tag
      run: docker tag Moudle8 wishy78/Moudle8:Moudle8

    - name: Login to Docker hub
      run: docker login --username wishy78 --password "${{ secrets.DOCKER_PASSWORD }}"

    - name: Publish to Docker hub
      run: docker push wishy78/Moudle8:Moudle8