name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.lock'
      - '.github\**'
      - '.idea\**'     
      - '.pytest_cache\**'
      - '.venv\**'
      - '.vscode\**'

  pull_request:
    paths-ignore:
      - '**.md'
      - '.github\**'
      - '.idea\**'     
      - '.vscode\**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: BuildTestImage
      run: docker build --target test --tag todo-app:test .
    
    - name: BuildAndTestImage
      run: docker run --env-file .env.test todo-app:test tests